### PR TITLE
Start 8u272 EA builds cycle

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes?

### CODE REVIEW

**Comment by jerboaa** [comment]
LGTM, but we should only merge once `b01` got tagged.

**Comment by jhuttana** [comment]
> LGTM, but we should only merge once `b01` got tagged.

Sure. Thank you!

**Comment by jerboaa** [comment]
@jhuttana Please rebase this on top of 8u265 and we can get it integrated. `jdk8u272-b01` has been tagged.

**Comment by jhuttana** [comment]
> @jhuttana Please rebase this on top of 8u265 and we can get it integrated. `jdk8u272-b01` has been tagged.

Sure. Thank you!

**Comment by jhuttana** [comment]
Could you please take a look is it okay to merge now?

**Review by jerboaa — APPROVED** [review]
LGTM

**Pull request merged**
