### PR TITLE
Move to git mirrors for builds

### LINKED ISSUE #13: Move to git mirrors for builds
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-December/014457.html announced JDK 8u's conversion to a mono-repository with a live git mirror. At this point it should be doable to produce upstream builds from git mirrors. We should switch to building from git mirrors by the time we do 8u332 EA builds (post January).

### PR DESCRIPTION
**Pull request by jhuttana**
Could you please review the changes?

### CODE REVIEW

**Comment by jhuttana** [comment]
I assume windows build scripts will be updated by @stooke

**Comment by stooke** [comment]
Working on it....

**Comment by jhuttana** [comment]
> Working on it....

@stooke Thank you so much !!

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by jhuttana** [comment]
> LGTM

Thank you!

**Comment by jerboaa** [comment]
Feel free to merge.

**Pull request merged**
